# -*- coding: utf-8 -*-
"""Bank Management System using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvHfUBIXDqwQ7Fo4qVQ32b4Pug5e1UV6
"""

class User():
  def __init__(self,name,age,gender):
    self.name= name
    self.age=age
    self.gender=gender
  def showdetail(self):
    print("Personal Details :")
    print(f"Name : {self.name.title()}")
    print(f"Age  : {self.age}")
    print(f"Gender : {self.gender.title()}")

swara = User("Swaranjali",22,"female")
swara.showdetail()

class bank(User):
  __balance = 0
  __usercount = 0
  def __init__(self,name,age,gender):
    super().__init__(name,age,gender)
    bank.__usercount +=1
    self.accountno = f"DenaBank000{bank.__usercount}"
  def ud(self):
    return self.__usercount
  def deposite(self,amount):
    self.amount =amount
    self.__balance += self.amount
    print(f"account balance is updated : Rs {self.__balance}")
  def withdraw(self,amount):
    self.amount = amount
    if (self.amount > self.__balance):
      print(f"Insufficient amount , Balance available : RS {self.__balance}")
    elif(100<=self.amount <=self.__balance):
      print("Thank you for visting")
      self.__balance = self.amount
  def viewbalance(self):
    self.showdetail()
    print(f"Account no : {self.accountno}")
    print(f"Current Balance is : {self.__balance}")
  def transfer(self,username,amount):
    self.amount=amount
    if(self.amount>self.__balance):
      print(f"Insufficient amount,balance available : RS{self.__balance}")
    elif (1<=self.amount<=self.__balance):
      username.__balance +=self.amount
      print("Amount transfer succesfully")
      print(f"Current balance is : {self.__balance}")
    else:
      print("You cannot transfer less than RS 1")

s = bank("swara",22,"female")
s.ud()

s.accountno

swara = bank("Swaranjali Shingate",22,"female")
sanha = bank("sanha shetty",22,"female")

swara.deposite(150000)

sanha.deposite(300000)

sanha.transfer(swara,13000)

swara.viewbalance()

